vich_uploader:
    db_driver: orm
    mappings:
        user_avatars:
            uri_prefix:         %app.user.uri_prefix%
            upload_destination: %app.user.avatars_path%
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
