# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.service.request_parser:
        class: AppBundle\Services\RequestParserService

    app.service.data_table:
        class: AppBundle\Services\DataTableService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.service.request_parser"
            - "@jms_serializer"
            - "@fos_js_routing.encoder"
            - "@fos_js_routing.normalizer"
