# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.service.request_parser:
        class: AppBundle\Services\RequestParserService

    app.service.data_table:
        class: AppBundle\Services\DataTableService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.service.request_parser"
            - "@jms_serializer"
            - "@fos_js_routing.encoder"
            - "@fos_js_routing.normalizer"

    app.service.user:
        class: AppBundle\Services\UserService

    app.service.course_attachment_directory_namer:
        class: AppBundle\Services\DirectoryNamer
        arguments: [%kernel.root_dir%]

### HANDLERS ###
    app.security.main.access_denied_handler:
        class: AppBundle\Security\AccessDeniedMainHandler
        arguments:
            - "@twig"

### VOTERS ###
    app.user_voter:
        class: AppBundle\Security\UserVoter
        tags:
            - { name: security.voter }
        public: false

    app.course_voter:
        class: AppBundle\Security\CourseVoter
        tags:
            - { name: security.voter }
        public: false

    app.module_voter:
        class: AppBundle\Security\ModuleVoter
        tags:
            - { name: security.voter }
        public: false

    app.homework_voter:
        class: AppBundle\Security\HomeworkVoter
        tags:
            - { name: security.voter }
        public: false